// Copyright 2026, OpenTeams.
// SPDX-License-Identifier: Apache-2.0

// Package accessrequests provides a bbolt-backed store for service access
// requests submitted by users. Access requests flow through these endpoints:
//
//	POST /api/v1/services/{id}/request_access
//	  → Create() — status: pending; deduplicates per (userID, serviceUID)
//
//	GET  /api/v1/admin/access-requests          → ListAll() / ListPending()
//	PUT  /api/v1/admin/access-requests/{id}/approve → UpdateStatus(id, Approved, by)
//	PUT  /api/v1/admin/access-requests/{id}/deny    → UpdateStatus(id, Denied,   by)
//
// Approving via the API currently only updates the record's status; adding the
// user to the Keycloak group (Phase 2) requires an admin service-account integration.
package accessrequests

import (
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"time"

	"github.com/google/uuid"
	bbolt "go.etcd.io/bbolt"
)

const bucketName = "access_requests"

// Status represents the lifecycle state of an AccessRequest.
type Status string

const (
	StatusPending  Status = "pending"
	StatusApproved Status = "approved"
	StatusDenied   Status = "denied"
)

// AccessRequest records a user's request to access a private service.
type AccessRequest struct {
	// ID is the UUIDv4 primary key, generated by Create().
	ID string `json:"id"`
	// ServiceUID is the Kubernetes UID of the target NebariApp.
	ServiceUID string `json:"serviceUID"`
	// ServiceName is the human-readable name of the service at request time.
	ServiceName string `json:"serviceName"`
	// UserID is the caller's preferred_username (or JWT sub fallback).
	UserID string `json:"userID"`
	// UserEmail is included when present in the JWT claims.
	UserEmail string `json:"userEmail,omitempty"`
	// Message is an optional free-text note from the requester.
	Message string `json:"message,omitempty"`
	// Status is the current lifecycle state.
	Status Status `json:"status"`
	// RequestedAt is the UTC timestamp when the request was created.
	RequestedAt time.Time `json:"requestedAt"`
	// ResolvedAt is set when the request is approved or denied.
	ResolvedAt *time.Time `json:"resolvedAt,omitempty"`
	// ResolvedBy is the admin username who approved or denied the request.
	ResolvedBy string `json:"resolvedBy,omitempty"`
}

// Sentinel errors returned by Store operations.
var (
	// ErrDuplicatePending is returned by Create when a pending request already
	// exists for the same (userID, serviceUID) pair.
	ErrDuplicatePending = errors.New("a pending access request already exists for this user and service")

	// ErrNotFound is returned when a request ID does not exist in the store.
	ErrNotFound = errors.New("access request not found")
)

// Store is a bbolt-backed persistent store for AccessRequest records.
type Store struct {
	db *bbolt.DB
}

// NewStore opens (or creates) the bbolt database at dbPath and returns a
// ready-to-use Store. The caller must call Close() when done.
func NewStore(dbPath string) (*Store, error) {
	db, err := bbolt.Open(dbPath, 0o600, nil)
	if err != nil {
		return nil, fmt.Errorf("opening access request store at %q: %w", dbPath, err)
	}
	err = db.Update(func(tx *bbolt.Tx) error {
		_, err := tx.CreateBucketIfNotExists([]byte(bucketName))
		return err
	})
	if err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("creating access_requests bucket: %w", err)
	}
	return &Store{db: db}, nil
}

// Close releases the underlying database file.
func (s *Store) Close() error {
	return s.db.Close()
}

// Create stores a new pending access request.
//
// Returns ErrDuplicatePending without writing if a pending request already
// exists for the same (userID, serviceUID) pair — prevents admin-queue spam.
func (s *Store) Create(serviceUID, serviceName, userID, userEmail, message string) (*AccessRequest, error) {
	req := &AccessRequest{
		ID:          uuid.NewString(),
		ServiceUID:  serviceUID,
		ServiceName: serviceName,
		UserID:      userID,
		UserEmail:   userEmail,
		Message:     message,
		Status:      StatusPending,
		RequestedAt: time.Now().UTC(),
	}
	err := s.db.Update(func(tx *bbolt.Tx) error {
		b := tx.Bucket([]byte(bucketName))
		// Deduplication scan — O(n) over existing requests; acceptable for this scale.
		cur := b.Cursor()
		for k, v := cur.First(); k != nil; k, v = cur.Next() {
			var existing AccessRequest
			if err := json.Unmarshal(v, &existing); err != nil {
				continue // skip corrupt entry
			}
			if existing.UserID == userID &&
				existing.ServiceUID == serviceUID &&
				existing.Status == StatusPending {
				return ErrDuplicatePending
			}
		}
		data, err := json.Marshal(req)
		if err != nil {
			return err
		}
		return b.Put([]byte(req.ID), data)
	})
	if err != nil {
		return nil, err
	}
	return req, nil
}

// Get retrieves a single access request by ID.
// Returns ErrNotFound when the ID does not exist.
func (s *Store) Get(id string) (*AccessRequest, error) {
	var req AccessRequest
	err := s.db.View(func(tx *bbolt.Tx) error {
		v := tx.Bucket([]byte(bucketName)).Get([]byte(id))
		if v == nil {
			return ErrNotFound
		}
		return json.Unmarshal(v, &req)
	})
	if err != nil {
		return nil, err
	}
	return &req, nil
}

// ListAll returns every stored access request, newest first.
func (s *Store) ListAll() ([]*AccessRequest, error) {
	return s.list(func(_ *AccessRequest) bool { return true })
}

// ListPending returns only requests with status=pending, newest first.
func (s *Store) ListPending() ([]*AccessRequest, error) {
	return s.list(func(r *AccessRequest) bool { return r.Status == StatusPending })
}

// ListForUser returns all requests submitted by userID, newest first.
func (s *Store) ListForUser(userID string) ([]*AccessRequest, error) {
	return s.list(func(r *AccessRequest) bool { return r.UserID == userID })
}

func (s *Store) list(filter func(*AccessRequest) bool) ([]*AccessRequest, error) {
	var out []*AccessRequest
	err := s.db.View(func(tx *bbolt.Tx) error {
		return tx.Bucket([]byte(bucketName)).ForEach(func(_, v []byte) error {
			var r AccessRequest
			if err := json.Unmarshal(v, &r); err != nil {
				return nil // skip corrupt entries
			}
			if filter(&r) {
				out = append(out, &r)
			}
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].RequestedAt.After(out[j].RequestedAt)
	})
	return out, nil
}

// UpdateStatus transitions an access request to Approved or Denied and records
// who performed the resolution. Returns the updated request.
// Returns ErrNotFound when the ID does not exist.
func (s *Store) UpdateStatus(id string, status Status, resolvedBy string) (*AccessRequest, error) {
	var updated AccessRequest
	err := s.db.Update(func(tx *bbolt.Tx) error {
		b := tx.Bucket([]byte(bucketName))
		v := b.Get([]byte(id))
		if v == nil {
			return ErrNotFound
		}
		if err := json.Unmarshal(v, &updated); err != nil {
			return err
		}
		now := time.Now().UTC()
		updated.Status = status
		updated.ResolvedAt = &now
		updated.ResolvedBy = resolvedBy
		data, err := json.Marshal(&updated)
		if err != nil {
			return err
		}
		return b.Put([]byte(id), data)
	})
	if err != nil {
		return nil, err
	}
	return &updated, nil
}
