// Copyright 2026, OpenTeams.
// SPDX-License-Identifier: Apache-2.0

// Package notifications provides a bbolt-backed store for platform notifications.
//
// Notifications are global records (they appear for every user). Per-user read
// state is tracked separately so a notification can be returned as read:true for
// one user and read:false for another without duplicating content.
//
// Routes served by this store:
//
//	GET  /api/v1/notifications              -> List() + ReadSet(userID)
//	PUT  /api/v1/notifications/{id}/read    -> MarkRead(userID, id)
//	POST /api/v1/admin/notifications        -> Create(image, title, message)
package notifications

import (
	"encoding/json"
	"errors"
	"fmt"
	"sort"
	"time"

	"github.com/google/uuid"
	bbolt "go.etcd.io/bbolt"
)

const (
	// notifBucket stores Notification records keyed by notification ID.
	notifBucket = "notifications"
	// readsBucket stores per-user read markers. Key format: "<userID>\x00<notifID>".
	readsBucket = "notification_reads"
)

// ErrNotFound is returned when a notification ID does not exist.
var ErrNotFound = errors.New("notification not found")

// Notification is the canonical record stored in the database.
type Notification struct {
	// ID is the UUIDv4 primary key, generated by Create().
	ID string `json:"id"`
	// Image is an optional URL or icon identifier shown in the notification card.
	Image string `json:"image,omitempty"`
	// Title is the short heading of the notification.
	Title string `json:"title"`
	// Message is the body text of the notification.
	Message string `json:"message"`
	// CreatedAt is the UTC timestamp when the notification was created.
	CreatedAt time.Time `json:"createdAt"`
}

// Store is a bbolt-backed store for notifications and per-user read state.
type Store struct {
	db *bbolt.DB
}

// NewStore opens (or creates) the bbolt database at dbPath and returns a
// ready-to-use Store. The caller must call Close() when done.
func NewStore(dbPath string) (*Store, error) {
	db, err := bbolt.Open(dbPath, 0o600, nil)
	if err != nil {
		return nil, fmt.Errorf("opening notifications store at %q: %w", dbPath, err)
	}
	err = db.Update(func(tx *bbolt.Tx) error {
		if _, err := tx.CreateBucketIfNotExists([]byte(notifBucket)); err != nil {
			return err
		}
		_, err := tx.CreateBucketIfNotExists([]byte(readsBucket))
		return err
	})
	if err != nil {
		_ = db.Close()
		return nil, fmt.Errorf("initialising notifications buckets: %w", err)
	}
	return &Store{db: db}, nil
}

// Close releases the underlying database file.
func (s *Store) Close() error {
	return s.db.Close()
}

// Create stores a new notification and returns it. image may be empty.
func (s *Store) Create(image, title, message string) (*Notification, error) {
	n := &Notification{
		ID:        uuid.NewString(),
		Image:     image,
		Title:     title,
		Message:   message,
		CreatedAt: time.Now().UTC(),
	}
	err := s.db.Update(func(tx *bbolt.Tx) error {
		data, err := json.Marshal(n)
		if err != nil {
			return err
		}
		return tx.Bucket([]byte(notifBucket)).Put([]byte(n.ID), data)
	})
	if err != nil {
		return nil, err
	}
	return n, nil
}

// Get retrieves a single notification by ID. Returns ErrNotFound when absent.
func (s *Store) Get(id string) (*Notification, error) {
	var n Notification
	err := s.db.View(func(tx *bbolt.Tx) error {
		v := tx.Bucket([]byte(notifBucket)).Get([]byte(id))
		if v == nil {
			return ErrNotFound
		}
		return json.Unmarshal(v, &n)
	})
	if err != nil {
		return nil, err
	}
	return &n, nil
}

// List returns all notifications, newest first.
func (s *Store) List() ([]*Notification, error) {
	var out []*Notification
	err := s.db.View(func(tx *bbolt.Tx) error {
		return tx.Bucket([]byte(notifBucket)).ForEach(func(_, v []byte) error {
			var n Notification
			if err := json.Unmarshal(v, &n); err != nil {
				return nil // skip corrupt entries
			}
			out = append(out, &n)
			return nil
		})
	})
	if err != nil {
		return nil, err
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].CreatedAt.After(out[j].CreatedAt)
	})
	return out, nil
}

// readsKey returns the composite bbolt key for the reads bucket.
func readsKey(userID, notifID string) []byte {
	return []byte(userID + "\x00" + notifID)
}

// MarkRead records that userID has read notifID. Returns ErrNotFound when the
// notification ID does not exist. Calling MarkRead on an already-read
// notification is idempotent.
func (s *Store) MarkRead(userID, notifID string) error {
	return s.db.Update(func(tx *bbolt.Tx) error {
		// Verify the notification exists before recording a read.
		if tx.Bucket([]byte(notifBucket)).Get([]byte(notifID)) == nil {
			return ErrNotFound
		}
		ts, _ := time.Now().UTC().MarshalText()
		return tx.Bucket([]byte(readsBucket)).Put(readsKey(userID, notifID), ts)
	})
}

// ReadSet returns a set of notification IDs that userID has already read.
// The returned map is safe to query with m[id]; absent keys are unread.
func (s *Store) ReadSet(userID string) (map[string]bool, error) {
	prefix := []byte(userID + "\x00")
	out := map[string]bool{}
	err := s.db.View(func(tx *bbolt.Tx) error {
		c := tx.Bucket([]byte(readsBucket)).Cursor()
		for k, _ := c.Seek(prefix); k != nil; k, _ = c.Next() {
			if len(k) < len(prefix) || string(k[:len(prefix)]) != string(prefix) {
				break
			}
			out[string(k[len(prefix):])] = true
		}
		return nil
	})
	return out, err
}
