{{- define "gvList" -}}
{{- $groupVersions := . -}}
<!--
  This file is auto-generated by crd-ref-docs from api/v1/.
  Do not edit manually. Run `make docs` to regenerate after changing Go types.
-->

# API Reference

This reference documents all CRD types exposed by the Nebari Operator.
For configuration examples and usage guides, see the [Configuration Reference](configuration-reference.md).

## Packages
{{- range $groupVersions }}
- {{ markdownRenderGVLink . }}
{{- end }}

{{ range $groupVersions }}
{{ template "gvDetails" . }}
{{ end }}
{{- end -}}
