{{- if and .Values.navigator .Values.navigator.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ include "nebari-operator.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: navigator
    name: {{ include "nebari-operator.navigatorName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
