{{- if .Values.navigator.enable }}
apiVersion: v1
kind: Service
metadata:
    labels:
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ include "nebari-operator.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: navigator
    name: {{ include "nebari-operator.resourceName" (dict "suffix" "navigator" "context" $) }}
    namespace: {{ .Release.Namespace }}
spec:
    type: {{ .Values.navigator.service.type }}
    ports:
        - port: {{ .Values.navigator.service.port }}
          targetPort: 8080
          protocol: TCP
          name: http
    selector:
        app.kubernetes.io/name: {{ include "nebari-operator.name" . }}
        app.kubernetes.io/component: navigator
{{- end }}
