apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nebari-service-discovery-reader
rules:
  - apiGroups:
      - reconcilers.nebari.dev
    resources:
      - nebariapps
    verbs:
      - get
      - list
      - watch
