apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nebari-system

resources:
  - service_account.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service.yaml
  - nebariapp.yaml

images:
  - name: service-discovery
    newName: quay.io/nebari/service-discovery-api
    newTag: latest
